version: '3'

services:
  db:
    image: postgres

  web:
    build: .
    entrypoint: /entrypoint.sh
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  db-admin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db