version: '3'

services:
  db:
    image: postgres

  web:
    build: .
    entrypoint: /entrypoint.sh
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db-admin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - db