version: '3'

services:
  db:
    container_name: lazyguys_db
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    container_name: lazyguys_web
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    env_file: .env
    volumes:
      - .:/code
      - static-content:/code/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    container_name: lazyguys_nginx
    build: config/nginx
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - static-content:/static
    depends_on:
      - web

  db-admin:
    container_name: lazyguys_db_admin
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  static-content: