# Generated by Django 2.1.7 on 2019-02-19 22:36

import os
from django.db import migrations
from django.contrib.auth.admin import User
from django.utils import timezone


def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = os.environ.get('ADMIN_USERNAME')
    superuser.email = os.environ.get('ADMIN_EMAIL')
    superuser.last_login = timezone.now()
    superuser.set_password(os.environ.get('ADMIN_PASSWORD'))
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
