# Generated by Django 2.1.7 on 2019-03-18 07:54

import os
from django.db import migrations
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):
        DJANGO_SU_NAME = os.environ.get('DJANGO_ADMIN_USERNAME')
        DJANGO_SU_EMAIL = os.environ.get('DJANGO_ADMIN_EMAIL')
        DJANGO_SU_PASSWORD = os.environ.get('DJANGO_ADMIN_PASSWORD')
        
        superuser = get_user_model().objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD
        )
        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
