# Generated by Django 2.1.7 on 2019-02-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_business_category_menu_menuitem_menuitemmodification_schedule_scheduleexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.Business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(related_name='menus', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='api.Business'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Menu'),
        ),
    ]
