# Generated by Django 2.1.7 on 2019-04-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190318_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('business__name', 'name'), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['business__name', 'name']},
        ),
        migrations.AlterField(
            model_name='menuitemmodification',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='api.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitemmodification',
            name='value',
            field=models.IntegerField(default=0, help_text='How much to add to price? If discount, insert negative number'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available', to='api.Business'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available', to='api.Menu'),
        ),
    ]
