# Generated by Django 2.1.7 on 2019-02-27 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190226_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='menus', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='items', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
