# Generated by Django 2.1.7 on 2019-02-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190227_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.Business'),
        ),
    ]
