# Generated by Django 2.1.7 on 2019-02-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190227_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
