# Generated by Django 2.1.7 on 2019-02-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190227_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available', to='api.Menu'),
        ),
    ]
